name: smart_responsive
description: A responsive ui builder for flutter
version: 0.0.1
author: Sayeed Afridi
homepage: https://sayeedafridi.github.io/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
